[package]
name = "sails-decl-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "sails-decl-rs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
glob = "0.3.3"
sails-decl-core = { path = "../sails-decl-core" }
