[package]
name = "sails-decl-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
sails-decl-core = { path = "../sails-decl-core" }
swc_ecma_codegen = "23.0.0"

